
package stubs.cart;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CartWebService", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CartWebService {


    /**
     * 
     * @param customerName
     * @return
     *     returns java.util.List<stubs.cart.Advantage>
     * @throws UnknownCustomerException_Exception
     */
    @WebMethod
    @WebResult(name = "cart_contents", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerCartContents", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.cart.GetCustomerCartContents")
    @ResponseWrapper(localName = "getCustomerCartContentsResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.cart.GetCustomerCartContentsResponse")
    public List<Advantage> getCustomerCartContents(
        @WebParam(name = "customer_name", targetNamespace = "")
        String customerName)
        throws UnknownCustomerException_Exception
    ;

    /**
     * 
     * @param quantity
     * @param id
     * @param customerName
     * @throws UncheckedException_Exception
     * @throws UnknownCustomerException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addAdvantageToCustomerCart", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.cart.AddAdvantageToCustomerCart")
    @ResponseWrapper(localName = "addAdvantageToCustomerCartResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.cart.AddAdvantageToCustomerCartResponse")
    public void addAdvantageToCustomerCart(
        @WebParam(name = "customer_name", targetNamespace = "")
        String customerName,
        @WebParam(name = "quantity", targetNamespace = "")
        int quantity,
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws UncheckedException_Exception, UnknownCustomerException_Exception
    ;

    /**
     * 
     * @param quantity
     * @param id
     * @param customerName
     * @throws UnknownCustomerException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeAdvantageToCustomerCart", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.cart.RemoveAdvantageToCustomerCart")
    @ResponseWrapper(localName = "removeAdvantageToCustomerCartResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.cart.RemoveAdvantageToCustomerCartResponse")
    public void removeAdvantageToCustomerCart(
        @WebParam(name = "customer_name", targetNamespace = "")
        String customerName,
        @WebParam(name = "quantity", targetNamespace = "")
        int quantity,
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws UnknownCustomerException_Exception
    ;

}
