
package stubs.cart;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UncheckedException", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
public class UncheckedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UncheckedException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UncheckedException_Exception(String message, UncheckedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UncheckedException_Exception(String message, UncheckedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: stubs.cart.UncheckedException
     */
    public UncheckedException getFaultInfo() {
        return faultInfo;
    }

}
