
package stubs.catalogue;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CatalogueServiceImplService", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/catalogue", wsdlLocation = "file:/home/user/Archi/master/client/src/main/resources/CatalogueWS.wsdl")
public class CatalogueServiceImplService
    extends Service
{

    private final static URL CATALOGUESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATALOGUESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CATALOGUESERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/catalogue", "CatalogueServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/user/Archi/master/client/src/main/resources/CatalogueWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATALOGUESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CATALOGUESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CatalogueServiceImplService() {
        super(__getWsdlLocation(), CATALOGUESERVICEIMPLSERVICE_QNAME);
    }

    public CatalogueServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATALOGUESERVICEIMPLSERVICE_QNAME, features);
    }

    public CatalogueServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CATALOGUESERVICEIMPLSERVICE_QNAME);
    }

    public CatalogueServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATALOGUESERVICEIMPLSERVICE_QNAME, features);
    }

    public CatalogueServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogueServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CatalogueService
     */
    @WebEndpoint(name = "CatalogueServiceImplPort")
    public CatalogueService getCatalogueServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/catalogue", "CatalogueServiceImplPort"), CatalogueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogueService
     */
    @WebEndpoint(name = "CatalogueServiceImplPort")
    public CatalogueService getCatalogueServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/catalogue", "CatalogueServiceImplPort"), CatalogueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATALOGUESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CATALOGUESERVICEIMPLSERVICE_EXCEPTION;
        }
        return CATALOGUESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
