
package stubs.traderCare;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TraderCareServiceImplService", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/trader-care", wsdlLocation = "file:/home/user/Archi/master/client/src/main/resources/TraderCareWS.wsdl")
public class TraderCareServiceImplService
    extends Service
{

    private final static URL TRADERCARESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRADERCARESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TRADERCARESERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/trader-care", "TraderCareServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/user/Archi/master/client/src/main/resources/TraderCareWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRADERCARESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TRADERCARESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TraderCareServiceImplService() {
        super(__getWsdlLocation(), TRADERCARESERVICEIMPLSERVICE_QNAME);
    }

    public TraderCareServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRADERCARESERVICEIMPLSERVICE_QNAME, features);
    }

    public TraderCareServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TRADERCARESERVICEIMPLSERVICE_QNAME);
    }

    public TraderCareServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRADERCARESERVICEIMPLSERVICE_QNAME, features);
    }

    public TraderCareServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TraderCareServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TraderCareService
     */
    @WebEndpoint(name = "TraderCareServiceImplPort")
    public TraderCareService getTraderCareServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/trader-care", "TraderCareServiceImplPort"), TraderCareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TraderCareService
     */
    @WebEndpoint(name = "TraderCareServiceImplPort")
    public TraderCareService getTraderCareServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/trader-care", "TraderCareServiceImplPort"), TraderCareService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRADERCARESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TRADERCARESERVICEIMPLSERVICE_EXCEPTION;
        }
        return TRADERCARESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
