
package stubs.adminCare;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdminCareService", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdminCareService {


    /**
     * 
     * @param adminName
     * @param customerPassword
     * @param adminMail
     * @throws AlreadyExistingAdminException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.adminCare.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.adminCare.RegisterResponse")
    public void register(
        @WebParam(name = "admin_name", targetNamespace = "")
        String adminName,
        @WebParam(name = "admin_mail", targetNamespace = "")
        String adminMail,
        @WebParam(name = "customer_password", targetNamespace = "")
        String customerPassword)
        throws AlreadyExistingAdminException_Exception
    ;

}
