
package stubs.adminCare;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminCareServiceImplService", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/admin-care", wsdlLocation = "file:/home/user/Archi/master/client/src/main/resources/AdminCareWS.wsdl")
public class AdminCareServiceImplService
    extends Service
{

    private final static URL ADMINCARESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINCARESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ADMINCARESERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/admin-care", "AdminCareServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/user/Archi/master/client/src/main/resources/AdminCareWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINCARESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ADMINCARESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AdminCareServiceImplService() {
        super(__getWsdlLocation(), ADMINCARESERVICEIMPLSERVICE_QNAME);
    }

    public AdminCareServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINCARESERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminCareServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ADMINCARESERVICEIMPLSERVICE_QNAME);
    }

    public AdminCareServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINCARESERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminCareServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminCareServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdminCareService
     */
    @WebEndpoint(name = "AdminCareServiceImplPort")
    public AdminCareService getAdminCareServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/admin-care", "AdminCareServiceImplPort"), AdminCareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminCareService
     */
    @WebEndpoint(name = "AdminCareServiceImplPort")
    public AdminCareService getAdminCareServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/admin-care", "AdminCareServiceImplPort"), AdminCareService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINCARESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ADMINCARESERVICEIMPLSERVICE_EXCEPTION;
        }
        return ADMINCARESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
