
package stubs.adminCare;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AlreadyExistingAdminException", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
public class AlreadyExistingAdminException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AlreadyExistingAdminException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AlreadyExistingAdminException_Exception(String message, AlreadyExistingAdminException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AlreadyExistingAdminException_Exception(String message, AlreadyExistingAdminException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: stubs.adminCare.AlreadyExistingAdminException
     */
    public AlreadyExistingAdminException getFaultInfo() {
        return faultInfo;
    }

}
