
package stubs.customerCare;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerCareService", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerCareService {


    /**
     * 
     * @param customerMoney
     * @param customerName
     */
    @WebMethod
    @RequestWrapper(localName = "addMoney", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.AddMoney")
    @ResponseWrapper(localName = "addMoneyResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.AddMoneyResponse")
    public void addMoney(
        @WebParam(name = "customer_name", targetNamespace = "")
        String customerName,
        @WebParam(name = "customer_money", targetNamespace = "")
        int customerMoney);

    /**
     * 
     * @param customerCost
     * @param customerName
     */
    @WebMethod
    @RequestWrapper(localName = "pay", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.PayResponse")
    public void pay(
        @WebParam(name = "customer_name", targetNamespace = "")
        String customerName,
        @WebParam(name = "customer_cost", targetNamespace = "")
        int customerCost);

    /**
     * 
     * @param customerPassword
     * @param customerName
     * @throws UnknownCustomerException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.LoginResponse")
    public void login(
        @WebParam(name = "customer_name", targetNamespace = "")
        String customerName,
        @WebParam(name = "customer_password", targetNamespace = "")
        String customerPassword)
        throws UnknownCustomerException_Exception
    ;

    /**
     * 
     * @param customerAddress
     * @param vup
     * @param customerMail
     * @param customerPassword
     * @param customerName
     * @throws AlreadyExistingCustomerException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.RegisterResponse")
    public void register(
        @WebParam(name = "customer_name", targetNamespace = "")
        String customerName,
        @WebParam(name = "customer_address", targetNamespace = "")
        String customerAddress,
        @WebParam(name = "customer_mail", targetNamespace = "")
        String customerMail,
        @WebParam(name = "customer_password", targetNamespace = "")
        String customerPassword,
        @WebParam(name = "vup", targetNamespace = "")
        boolean vup)
        throws AlreadyExistingCustomerException_Exception
    ;

}
